export const LIST_CHECKLIST_CATEGORY_ATTEMPT = 'LIST_CHECKLIST_CATEGORY_ATTEMPT';
export const LIST_CHECKLIST_CATEGORY_SUCCESS = 'LIST_CHECKLIST_CATEGORY_SUCCESS';
export const LIST_CHECKLIST_CATEGORY_FAIL = 'LIST_CHECKLIST_CATEGORY_FAIL';

export const CREATE_CHECKLIST_CATEGORY_ATTEMPT = 'CREATE_CHECKLIST_CATEGORY_ATTEMPT';
export const CREATE_CHECKLIST_CATEGORY_SUCCESS = 'CREATE_CHECKLIST_CATEGORY_SUCCESS';
export const CREATE_CHECKLIST_CATEGORY_FAIL = 'CREATE_CHECKLIST_CATEGORY_FAIL';

export const DELETE_CHECKLIST_CATEGORY_ATTEMPT = 'DELETE_CHECKLIST_CATEGORY_ATTEMPT';
export const DELETE_CHECKLIST_CATEGORY_SUCCESS = 'DELETE_CHECKLIST_CATEGORY_SUCCESS';
export const DELETE_CHECKLIST_CATEGORY_FAIL = 'DELETE_CHECKLIST_CATEGORY_FAIL';

export const UPDATE_CHECKLIST_CATEGORY_ATTEMPT = 'UPDATE_CHECKLIST_CATEGORY_ATTEMPT';
export const UPDATE_CHECKLIST_CATEGORY_SUCCESS = 'UPDATE_CHECKLIST_CATEGORY_SUCCESS';
export const UPDATE_CHECKLIST_CATEGORY_FAIL = 'UPDATE_CHECKLIST_CATEGORY_FAIL';
