export const GET_COMPANY_INFO_ATTEMPT = 'GET_COMPANY_INFO_ATTEMPT';
export const GET_COMPANY_INFO_SUCCESS = 'GET_COMPANY_INFO_SUCCESS';
export const GET_COMPANY_INFO_FAIL = 'GET_COMPANY_INFO_FAIL';

export const UPDATE_COMPANY_INFO_ATTEMPT = 'UPDATE_COMPANY_INFO_ATTEMPT';
export const UPDATE_COMPANY_INFO_SUCCESS = 'UPDATE_COMPANY_INFO_SUCCESS';
export const UPDATE_COMPANY_INFO_FAIL = 'UPDATE_COMPANY_INFO_FAIL';
