export const LIST_FRIDGE_ITEM_ATTEMPT = 'LIST_FRIDGE_ITEM_ATTEMPT';
export const LIST_FRIDGE_ITEM_SUCCESS = 'LIST_FRIDGE_ITEM_SUCCESS';
export const LIST_FRIDGE_ITEM_FAIL = 'LIST_FRIDGE_ITEM_FAIL';

export const CREATE_FRIDGE_ITEM_ATTEMPT = 'CREATE_FRIDGE_ITEM_ATTEMPT';
export const CREATE_FRIDGE_ITEM_SUCCESS = 'CREATE_FRIDGE_ITEM_SUCCESS';
export const CREATE_FRIDGE_ITEM_FAIL = 'CREATE_FRIDGE_ITEM_FAIL';

export const DELETE_FRIDGE_ITEM_ATTEMPT = 'DELETE_FRIDGE_ITEM_ATTEMPT';
export const DELETE_FRIDGE_ITEM_SUCCESS = 'DELETE_FRIDGE_ITEM_SUCCESS';
export const DELETE_FRIDGE_ITEM_FAIL = 'DELETE_FRIDGE_ITEM_FAIL';

export const UPDATE_FRIDGE_ITEM_ATTEMPT = 'UPDATE_FRIDGE_ITEM_ATTEMPT';
export const UPDATE_FRIDGE_ITEM_SUCCESS = 'UPDATE_FRIDGE_ITEM_SUCCESS';
export const UPDATE_FRIDGE_ITEM_FAIL = 'UPDATE_FRIDGE_ITEM_FAIL';
