export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const PASSWORD_CHALLENGE_ATTEMPT = 'PASSWORD_CHALLENGE_ATTEMPT';
export const PASSWORD_CHALLENGE_SUCCESS = 'PASSWORD_CHALLENGE_SUCCESS';
export const PASSWORD_CHALLENGE_FAIL = 'PASSWORD_CHALLENGE_FAIL';

export const USER_AUTH_UPDATED = 'USER_AUTH_UPDATED';
