export const LIST_SAFETY_RECORD_TASK_ATTEMPT = 'LIST_SAFETY_RECORD_TASK_ATTEMPT';
export const LIST_SAFETY_RECORD_TASK_SUCCESS = 'LIST_SAFETY_RECORD_TASK_SUCCESS';
export const LIST_SAFETY_RECORD_TASK_FAIL = 'LIST_SAFETY_RECORD_TASK_FAIL';

export const CREATE_SAFETY_RECORD_TASK_ATTEMPT = 'CREATE_SAFETY_RECORD_TASK_ATTEMPT';
export const CREATE_SAFETY_RECORD_TASK_SUCCESS = 'CREATE_SAFETY_RECORD_TASK_SUCCESS';
export const CREATE_SAFETY_RECORD_TASK_FAIL = 'CREATE_SAFETY_RECORD_TASK_FAIL';

export const DELETE_SAFETY_RECORD_TASK_ATTEMPT = 'DELETE_SAFETY_RECORD_TASK_ATTEMPT';
export const DELETE_SAFETY_RECORD_TASK_SUCCESS = 'DELETE_SAFETY_RECORD_TASK_SUCCESS';
export const DELETE_SAFETY_RECORD_TASK_FAIL = 'DELETE_SAFETY_RECORD_TASK_FAIL';

export const UPDATE_SAFETY_RECORD_TASK_ATTEMPT = 'UPDATE_SAFETY_RECORD_TASK_ATTEMPT';
export const UPDATE_SAFETY_RECORD_TASK_SUCCESS = 'UPDATE_SAFETY_RECORD_TASK_SUCCESS';
export const UPDATE_SAFETY_RECORD_TASK_FAIL = 'UPDATE_SAFETY_RECORD_TASK_FAIL';
