export const LIST_FOOD_ITEM_ATTEMPT = 'LIST_FOOD_ITEM_ATTEMPT';
export const LIST_FOOD_ITEM_SUCCESS = 'LIST_FOOD_ITEM_SUCCESS';
export const LIST_FOOD_ITEM_FAIL = 'LIST_FOOD_ITEM_FAIL';

export const CREATE_FOOD_ITEM_ATTEMPT_ATTEMPT = 'CREATE_FOOD_ITEM_ATTEMPT_ATTEMPT';
export const CREATE_FOOD_ITEM_ATTEMPT_SUCCESS = 'CREATE_FOOD_ITEM_ATTEMPT_SUCCESS';
export const CREATE_FOOD_ITEM_ATTEMPT_FAIL = 'CREATE_FOOD_ITEM_ATTEMPT_FAIL';

export const DELETE_FOOD_ITEM_ATTEMPT_ATTEMPT = 'DELETE_FOOD_ITEM_ATTEMPT_ATTEMPT';
export const DELETE_FOOD_ITEM_ATTEMPT_SUCCESS = 'DELETE_FOOD_ITEM_ATTEMPT_SUCCESS';
export const DELETE_FOOD_ITEM_ATTEMPT_FAIL = 'DELETE_FOOD_ITEM_ATTEMPT_FAIL';
