export const COMPANY_INFO_FETCH = 'COMPANY_INFO_FETCH';
export const COMPANY_INFO_SUCCESS = 'COMPANY_INFO_SUCCESS';
export const COMPANY_INFO_FAIL = 'COMPANY_INFO_FAIL';

export const VALIDATE_TOKEN_ATTEMPT = 'VALIDATE_TOKEN_ATTEMPT';
export const VALIDATE_TOKEN_SUCCESS = 'VALIDATE_TOKEN_SUCCESS';
export const VALIDATE_TOKEN_FAIL = 'VALIDATE_TOKEN_FAIL';

export const SESSION_TIMEOUT = 'SESSION_TIMEOUT';
