export const LIST_SAFETY_ATTEMPT = 'LIST_SAFETY_ATTEMPT';
export const LIST_SAFETY_SUCCESS = 'LIST_SAFETY_SUCCESS';
export const LIST_SAFETY_FAIL = 'LIST_SAFETY_FAIL';

export const CREATE_SAFETY_ATTEMPT = 'CREATE_SAFETY_ATTEMPT';
export const CREATE_SAFETY_SUCCESS = 'CREATE_SAFETY_SUCCESS';
export const CREATE_SAFETY_FAIL = 'CREATE_SAFETY_FAIL';

export const DELETE_SAFETY_ATTEMPT = 'DELETE_SAFETY_ATTEMPT';
export const DELETE_SAFETY_SUCCESS = 'DELETE_SAFETY_SUCCESS';
export const DELETE_SAFETY_FAIL = 'DELETE_SAFETY_FAIL';

export const UPDATE_SAFETY_ATTEMPT = 'UPDATE_SAFETY_ATTEMPT';
export const UPDATE_SAFETY_SUCCESS = 'UPDATE_SAFETY_SUCCESS';
export const UPDATE_SAFETY_FAIL = 'UPDATE_SAFETY_FAIL';
