export const DASHBOARD_LOADING = 'DASHBOARD_LOADING';

export const DASHBOARD_SHOW_ERROR = 'DASHBOARD_SHOW_ERROR';
export const DASHBOARD_HIDE_ERROR = 'DASHBOARD_HIDE_ERROR';

export const DASHBOARD_SHOW_SUCCESS = 'DASHBOARD_SHOW_SUCCESS';
export const DASHBOARD_HIDE_SUCCESS = 'DASHBOARD_HIDE_SUCCESS';
