export const LIST_FAST_COOLING_ATTEMPT = 'LIST_FAST_COOLING_ATTEMPT';
export const LIST_FAST_COOLING_SUCCESS = 'LIST_FAST_COOLING_SUCCESS';
export const LIST_FAST_COOLING_FAIL = 'LIST_FAST_COOLING_FAIL';

export const CREATE_FAST_COOLING_ATTEMPT = 'CREATE_FAST_COOLING_ATTEMPT';
export const CREATE_FAST_COOLING_SUCCESS = 'CREATE_FAST_COOLING_SUCCESS';
export const CREATE_FAST_COOLING_FAIL = 'CREATE_FAST_COOLING_FAIL';

export const DELETE_FAST_COOLING_ATTEMPT = 'DELETE_FAST_COOLING_ATTEMPT';
export const DELETE_FAST_COOLING_SUCCESS = 'DELETE_FAST_COOLING_SUCCESS';
export const DELETE_FAST_COOLING_FAIL = 'DELETE_FAST_COOLING_FAIL';

export const UPDATE_FAST_COOLING_ATTEMPT = 'UPDATE_FAST_COOLING_ATTEMPT';
export const UPDATE_FAST_COOLING_SUCCESS = 'UPDATE_FAST_COOLING_SUCCESS';
export const UPDATE_FAST_COOLING_FAIL = 'UPDATE_FAST_COOLING_FAIL';
