export const LIST_FAST_COOLING_ATTEMPT = 'LIST_FAST_COOLING_ATTEMPT';
export const LIST_FAST_COOLING_SUCCESS = 'LIST_FAST_COOLING_SUCCESS';
export const LIST_FAST_COOLING_FAIL = 'LIST_FAST_COOLING_FAIL';
