export const LIST_FRIDGE_LOG_ATTEMPT = 'LIST_FRIDGE_LOG_ATTEMPT';
export const LIST_FRIDGE_LOG_SUCCESS = 'LIST_FRIDGE_LOG_SUCCESS';
export const LIST_FRIDGE_LOG_FAIL = 'LIST_FRIDGE_LOG_FAIL';

export const CREATE_FRIDGE_LOG_ATTEMPT = 'CREATE_FRIDGE_LOG_ATTEMPT';
export const CREATE_FRIDGE_LOG_SUCCESS = 'CREATE_FRIDGE_LOG_SUCCESS';
export const CREATE_FRIDGE_LOG_FAIL = 'CREATE_FRIDGE_LOG_FAIL';

export const DELETE_FRIDGE_LOG_ATTEMPT = 'DELETE_FRIDGE_LOG_ATTEMPT';
export const DELETE_FRIDGE_LOG_SUCCESS = 'DELETE_FRIDGE_LOG_SUCCESS';
export const DELETE_FRIDGE_LOG_FAIL = 'DELETE_FRIDGE_LOG_FAIL';

export const UPDATE_FRIDGE_LOG_ATTEMPT = 'UPDATE_FRIDGE_LOG_ATTEMPT';
export const UPDATE_FRIDGE_LOG_SUCCESS = 'UPDATE_FRIDGE_LOG_SUCCESS';
export const UPDATE_FRIDGE_LOG_FAIL = 'UPDATE_FRIDGE_LOG_FAIL';
