export const LIST_MEDICAL_LOG_ATTEMPT = 'LIST_MEDICAL_LOG_ATTEMPT';
export const LIST_MEDICAL_LOG_SUCCESS = 'LIST_MEDICAL_LOG_SUCCESS';
export const LIST_MEDICAL_LOG_FAIL = 'LIST_MEDICAL_LOG_FAIL';

export const CREATE_MEDICAL_LOG_ATTEMPT = 'CREATE_MEDICAL_LOG_ATTEMPT';
export const CREATE_MEDICAL_LOG_SUCCESS = 'CREATE_MEDICAL_LOG_SUCCESS';
export const CREATE_MEDICAL_LOG_FAIL = 'CREATE_MEDICAL_LOG_FAIL';

export const DELETE_MEDICAL_LOG_ATTEMPT = 'DELETE_MEDICAL_LOG_ATTEMPT';
export const DELETE_MEDICAL_LOG_SUCCESS = 'DELETE_MEDICAL_LOG_SUCCESS';
export const DELETE_MEDICAL_LOG_FAIL = 'DELETE_MEDICAL_LOG_FAIL';

export const UPDATE_MEDICAL_LOG_ATTEMPT = 'UPDATE_MEDICAL_LOG_ATTEMPT';
export const UPDATE_MEDICAL_LOG_SUCCESS = 'UPDATE_MEDICAL_LOG_SUCCESS';
export const UPDATE_MEDICAL_LOG_FAIL = 'UPDATE_MEDICAL_LOG_FAIL';
