export const LIST_HOT_HOLDING_ATTEMPT = 'LIST_HOT_HOLDING_ATTEMPT';
export const LIST_HOT_HOLDING_SUCCESS = 'LIST_HOT_HOLDING_SUCCESS';
export const LIST_HOT_HOLDING_FAIL = 'LIST_HOT_HOLDING_FAIL';

export const CREATE_HOT_HOLDING_ATTEMPT = 'CREATE_HOT_HOLDING_ATTEMPT';
export const CREATE_HOT_HOLDING_SUCCESS = 'CREATE_HOT_HOLDING_SUCCESS';
export const CREATE_HOT_HOLDING_FAIL = 'CREATE_HOT_HOLDING_FAIL';
