export const LIST_CLEANING_ITEM_ATTEMPT = 'LIST_CLEANING_ITEM_ATTEMPT';
export const LIST_CLEANING_ITEM_SUCCESS = 'LIST_CLEANING_ITEM_SUCCESS';
export const LIST_CLEANING_ITEM_FAIL = 'LIST_CLEANING_ITEM_FAIL';

export const CREATE_CLEANING_ITEM_ATTEMPT = 'CREATE_CLEANING_ITEM_ATTEMPT';
export const CREATE_CLEANING_ITEM_SUCCESS = 'CREATE_CLEANING_ITEM_SUCCESS';
export const CREATE_CLEANING_ITEM_FAIL = 'CREATE_CLEANING_ITEM_FAIL';

export const DELETE_CLEANING_ITEM_ATTEMPT = 'DELETE_CLEANING_ITEM_ATTEMPT';
export const DELETE_CLEANING_ITEM_SUCCESS = 'DELETE_CLEANING_ITEM_SUCCESS';
export const DELETE_CLEANING_ITEM_FAIL = 'DELETE_CLEANING_ITEM_FAIL';

export const UPDATE_CLEANING_ITEM_ATTEMPT = 'UPDATE_CLEANING_ITEM_ATTEMPT';
export const UPDATE_CLEANING_ITEM_SUCCESS = 'UPDATE_CLEANING_ITEM_SUCCESS';
export const UPDATE_CLEANING_ITEM_FAIL = 'UPDATE_CLEANING_ITEM_FAIL';
