export const LIST_SUPPLIER_ATTEMPT = 'LIST_SUPPLIER_ATTEMPT';
export const LIST_SUPPLIER_SUCCESS = 'LIST_SUPPLIER_SUCCESS';
export const LIST_SUPPLIER_FAIL = 'LIST_SUPPLIER_FAIL';

export const CREATE_SUPPLIER_ATTEMPT = 'CREATE_SUPPLIER_ATTEMPT';
export const CREATE_SUPPLIER_SUCCESS = 'CREATE_SUPPLIER_SUCCESS';
export const CREATE_SUPPLIER_FAIL = 'CREATE_SUPPLIER_FAIL';

export const DELETE_SUPPLIER_ATTEMPT = 'DELETE_SUPPLIER_ATTEMPT';
export const DELETE_SUPPLIER_SUCCESS = 'DELETE_SUPPLIER_SUCCESS';
export const DELETE_SUPPLIER_FAIL = 'DELETE_SUPPLIER_FAIL';

export const UPDATE_SUPPLIER_ATTEMPT = 'UPDATE_SUPPLIER_ATTEMPT';
export const UPDATE_SUPPLIER_SUCCESS = 'UPDATE_SUPPLIER_SUCCESS';
export const UPDATE_SUPPLIER_FAIL = 'UPDATE_SUPPLIER_FAIL';
