export const LIST_SERVICES_ATTEMPT = 'LIST_SERVICES_ATTEMPT';
export const LIST_SERVICES_SUCCESS = 'LIST_SERVICES_SUCCESS';
export const LIST_SERVICES_FAIL = 'LIST_SERVICES_FAIL';

export const CREATE_SERVICES_ATTEMPT = 'CREATE_SERVICES_ATTEMPT';
export const CREATE_SERVICES_SUCCESS = 'CREATE_SERVICES_SUCCESS';
export const CREATE_SERVICES_FAIL = 'CREATE_SERVICES_FAIL';

export const DELETE_SERVICES_ATTEMPT = 'DELETE_SERVICES_ATTEMPT';
export const DELETE_SERVICES_SUCCESS = 'DELETE_SERVICES_SUCCESS';
export const DELETE_SERVICES_FAIL = 'DELETE_SERVICES_FAIL';

export const UPDATE_SERVICES_ATTEMPT = 'UPDATE_SERVICES_ATTEMPT';
export const UPDATE_SERVICES_SUCCESS = 'UPDATE_SERVICES_SUCCESS';
export const UPDATE_SERVICES_FAIL = 'UPDATE_SERVICES_FAIL';