export const LIST_TRAINING_LOG_ATTEMPT = 'LIST_TRAINING_LOG_ATTEMPT';
export const LIST_TRAINING_LOG_SUCCESS = 'LIST_TRAINING_LOG_SUCCESS';
export const LIST_TRAINING_LOG_FAIL = 'LIST_TRAINING_LOG_FAIL';

export const CREATE_TRAINING_LOG_ATTEMPT = 'CREATE_TRAINING_LOG_ATTEMPT';
export const CREATE_TRAINING_LOG_SUCCESS = 'CREATE_TRAINING_LOG_SUCCESS';
export const CREATE_TRAINING_LOG_FAIL = 'CREATE_TRAINING_LOG_FAIL';

export const DELETE_TRAINING_LOG_ATTEMPT = 'DELETE_TRAINING_LOG_ATTEMPT';
export const DELETE_TRAINING_LOG_SUCCESS = 'DELETE_TRAINING_LOG_SUCCESS';
export const DELETE_TRAINING_LOG_FAIL = 'DELETE_TRAINING_LOG_FAIL';

export const UPDATE_TRAINING_LOG_ATTEMPT = 'UPDATE_TRAINING_LOG_ATTEMPT';
export const UPDATE_TRAINING_LOG_SUCCESS = 'UPDATE_TRAINING_LOG_SUCCESS';
export const UPDATE_TRAINING_LOG_FAIL = 'UPDATE_TRAINING_LOG_FAIL';
