export const LIST_SAFETY_RECORD_CATEGORY_ATTEMPT = 'LIST_SAFETY_RECORD_CATEGORY_ATTEMPT';
export const LIST_SAFETY_RECORD_CATEGORY_SUCCESS = 'LIST_SAFETY_RECORD_CATEGORY_SUCCESS';
export const LIST_SAFETY_RECORD_CATEGORY_FAIL = 'LIST_SAFETY_RECORD_CATEGORY_FAIL';

export const CREATE_SAFETY_RECORD_CATEGORY_ATTEMPT = 'CREATE_SAFETY_RECORD_CATEGORY_ATTEMPT';
export const CREATE_SAFETY_RECORD_CATEGORY_SUCCESS = 'CREATE_SAFETY_RECORD_CATEGORY_SUCCESS';
export const CREATE_SAFETY_RECORD_CATEGORY_FAIL = 'CREATE_SAFETY_RECORD_CATEGORY_FAIL';

export const DELETE_SAFETY_RECORD_CATEGORY_ATTEMPT = 'DELETE_SAFETY_RECORD_CATEGORY_ATTEMPT';
export const DELETE_SAFETY_RECORD_CATEGORY_SUCCESS = 'DELETE_SAFETY_RECORD_CATEGORY_SUCCESS';
export const DELETE_SAFETY_RECORD_CATEGORY_FAIL = 'DELETE_SAFETY_RECORD_CATEGORY_FAIL';

export const UPDATE_SAFETY_RECORD_CATEGORY_ATTEMPT = 'UPDATE_SAFETY_RECORD_CATEGORY_ATTEMPT';
export const UPDATE_SAFETY_RECORD_CATEGORY_SUCCESS = 'UPDATE_SAFETY_RECORD_CATEGORY_SUCCESS';
export const UPDATE_SAFETY_RECORD_CATEGORY_FAIL = 'UPDATE_SAFETY_RECORD_CATEGORY_FAIL';
