export const LIST_FREEZER_TASK_ATTEMPT = 'LIST_FREEZER_TASK_ATTEMPT';
export const LIST_FREEZER_TASK_SUCCESS = 'LIST_FREEZER_TASK_SUCCESS';
export const LIST_FREEZER_TASK_FAIL = 'LIST_FREEZER_TASK_FAIL';

export const CREATE_FREEZER_TASK_ATTEMPT = 'CREATE_FREEZER_TASK_ATTEMPT';
export const CREATE_FREEZER_TASK_SUCCESS = 'CREATE_FREEZER_TASK_SUCCESS';
export const CREATE_FREEZER_TASK_FAIL = 'CREATE_FREEZER_TASK_FAIL';
