export const CREATE_FREEZER_TASK_ATTEMPT = 'CREATE_FREEZER_TASK_ATTEMPT';
export const CREATE_FREEZER_TASK_SUCCESS = 'CREATE_FREEZER_TASK_SUCCESS';
export const CREATE_FREEZER_TASK_FAIL = 'CREATE_FREEZER_TASK_FAIL';
