export const LIST_CHECKLIST_ITEM_ATTEMPT = 'LIST_CHECKLIST_ITEM_ATTEMPT';
export const LIST_CHECKLIST_ITEM_SUCCESS = 'LIST_CHECKLIST_ITEM_SUCCESS';
export const LIST_CHECKLIST_ITEM_FAIL = 'LIST_CHECKLIST_ITEM_FAIL';

export const CREATE_CHECKLIST_ITEM_ATTEMPT = 'CREATE_CHECKLIST_ITEM_ATTEMPT';
export const CREATE_CHECKLIST_ITEM_SUCCESS = 'CREATE_CHECKLIST_ITEM_SUCCESS';
export const CREATE_CHECKLIST_ITEM_FAIL = 'CREATE_CHECKLIST_ITEM_FAIL';

export const DELETE_CHECKLIST_ITEM_ATTEMPT = 'DELETE_CHECKLIST_ITEM_ATTEMPT';
export const DELETE_CHECKLIST_ITEM_SUCCESS = 'DELETE_CHECKLIST_ITEM_SUCCESS';
export const DELETE_CHECKLIST_ITEM_FAIL = 'DELETE_CHECKLIST_ITEM_FAIL';

export const UPDATE_CHECKLIST_ITEM_ATTEMPT = 'UPDATE_CHECKLIST_ITEM_ATTEMPT';
export const UPDATE_CHECKLIST_ITEM_SUCCESS = 'UPDATE_CHECKLIST_ITEM_SUCCESS';
export const UPDATE_CHECKLIST_ITEM_FAIL = 'UPDATE_CHECKLIST_ITEM_FAIL';
