export const LIST_PEST_ATTEMPT = 'LIST_PEST_ATTEMPT';
export const LIST_PEST_SUCCESS = 'LIST_PEST_SUCCESS';
export const LIST_PEST_FAIL = 'LIST_PEST_FAIL';

export const CREATE_PEST_ATTEMPT = 'CREATE_PEST_ATTEMPT';
export const CREATE_PEST_SUCCESS = 'CREATE_PEST_SUCCESS';
export const CREATE_PEST_FAIL = 'CREATE_PEST_FAIL';

export const DELETE_PEST_ATTEMPT = 'DELETE_PEST_ATTEMPT';
export const DELETE_PEST_SUCCESS = 'DELETE_PEST_SUCCESS';
export const DELETE_PEST_FAIL = 'DELETE_PEST_FAIL';

export const UPDATE_PEST_ATTEMPT = 'UPDATE_PEST_ATTEMPT';
export const UPDATE_PEST_SUCCESS = 'UPDATE_PEST_SUCCESS';
export const UPDATE_PEST_FAIL = 'UPDATE_PEST_FAIL';
