export const LIST_TEAM_ITEM_ATTEMPT = 'LIST_TEAM_ITEM_ATTEMPT';
export const LIST_TEAM_ITEM_SUCCESS = 'LIST_TEAM_ITEM_SUCCESS';
export const LIST_TEAM_ITEM_FAIL = 'LIST_TEAM_ITEM_FAIL';

export const CREATE_TEAM_ITEM_ATTEMPT = 'CREATE_TEAM_ITEM_ATTEMPT';
export const CREATE_TEAM_ITEM_SUCCESS = 'CREATE_TEAM_ITEM_SUCCESS';
export const CREATE_TEAM_ITEM_FAIL = 'CREATE_TEAM_ITEM_FAIL';

export const DELETE_TEAM_ITEM_ATTEMPT = 'DELETE_TEAM_ITEM_ATTEMPT';
export const DELETE_TEAM_ITEM_SUCCESS = 'DELETE_TEAM_ITEM_SUCCESS';
export const DELETE_TEAM_ITEM_FAIL = 'DELETE_TEAM_ITEM_FAIL';

export const UPDATE_TEAM_ITEM_ATTEMPT = 'UPDATE_TEAM_ITEM_ATTEMPT';
export const UPDATE_TEAM_ITEM_SUCCESS = 'UPDATE_TEAM_ITEM_SUCCESS';
export const UPDATE_TEAM_ITEM_FAIL = 'UPDATE_TEAM_ITEM_FAIL';
