export const USER_PROFILE_UPDATE_ATTEMPT = 'USER_PROFILE_UPDATE_ATTEMPT';
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS';
export const USER_PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL';

export const USER_AUTH_UPDATED = 'USER_AUTH_UPDATED';
export const USER_AUTH_LOGOUT = 'USER_AUTH_LOGOUT';
