export const LIST_REPORT_ATTEMPT = 'LIST_REPORT_ATTEMPT';
export const LIST_REPORT_SUCCESS = 'LIST_REPORT_SUCCESS';
export const LIST_REPORT_FAIL = 'LIST_REPORT_FAIL';

export const CREATE_REPORT_ATTEMPT = 'CREATE_REPORT_ATTEMPT';
export const CREATE_REPORT_SUCCESS = 'CREATE_REPORT_SUCCESS';
export const CREATE_REPORT_FAIL = 'CREATE_REPORT_FAIL';

export const DELETE_REPORT_ATTEMPT = 'DELETE_REPORT_ATTEMPT';
export const DELETE_REPORT_SUCCESS = 'DELETE_REPORT_SUCCESS';
export const DELETE_REPORT_FAIL = 'DELETE_REPORT_FAIL';

export const UPDATE_REPORT_ATTEMPT = 'UPDATE_REPORT_ATTEMPT';
export const UPDATE_REPORT_SUCCESS = 'UPDATE_REPORT_SUCCESS';
export const UPDATE_REPORT_FAIL = 'UPDATE_REPORT_FAIL';
