export const CREATE_FRIDGE_TASK_ATTEMPT = 'CREATE_FRIDGE_TASK_ATTEMPT';
export const CREATE_FRIDGE_TASK_SUCCESS = 'CREATE_FRIDGE_TASK_SUCCESS';
export const CREATE_FRIDGE_TASK_FAIL = 'CREATE_FRIDGE_TASK_FAIL';
