export const LIST_FRIDGE_TASK_ATTEMPT = 'LIST_FRIDGE_TASK_ATTEMPT';
export const LIST_FRIDGE_TASK_SUCCESS = 'LIST_FRIDGE_TASK_SUCCESS';
export const LIST_FRIDGE_TASK_FAIL = 'LIST_FRIDGE_TASK_FAIL';

export const CREATE_FRIDGE_TASK_ATTEMPT = 'CREATE_FRIDGE_TASK_ATTEMPT';
export const CREATE_FRIDGE_TASK_SUCCESS = 'CREATE_FRIDGE_TASK_SUCCESS';
export const CREATE_FRIDGE_TASK_FAIL = 'CREATE_FRIDGE_TASK_FAIL';
