export const LIST_CLEANING_LOG_ATTEMPT = 'LIST_CLEANING_LOG_ATTEMPT';
export const LIST_CLEANING_LOG_SUCCESS = 'LIST_CLEANING_LOG_SUCCESS';
export const LIST_CLEANING_LOG_FAIL = 'LIST_CLEANING_LOG_FAIL';

export const CREATE_CLEANING_LOG_ATTEMPT = 'CREATE_CLEANING_LOG_ATTEMPT';
export const CREATE_CLEANING_LOG_SUCCESS = 'CREATE_CLEANING_LOG_SUCCESS';
export const CREATE_CLEANING_LOG_FAIL = 'CREATE_CLEANING_LOG_FAIL';

export const DELETE_CLEANING_LOG_ATTEMPT = 'DELETE_CLEANING_LOG_ATTEMPT';
export const DELETE_CLEANING_LOG_SUCCESS = 'DELETE_CLEANING_LOG_SUCCESS';
export const DELETE_CLEANING_LOG_FAIL = 'DELETE_CLEANING_LOG_FAIL';

export const UPDATE_CLEANING_LOG_ATTEMPT = 'UPDATE_CLEANING_LOG_ATTEMPT';
export const UPDATE_CLEANING_LOG_SUCCESS = 'UPDATE_CLEANING_LOG_SUCCESS';
export const UPDATE_CLEANING_LOG_FAIL = 'UPDATE_CLEANING_LOG_FAIL';
