export const LIST_FREEZER_LOG_ATTEMPT = 'LIST_FREEZER_LOG_ATTEMPT';
export const LIST_FREEZER_LOG_SUCCESS = 'LIST_FREEZER_LOG_SUCCESS';
export const LIST_FREEZER_LOG_FAIL = 'LIST_FREEZER_LOG_FAIL';

export const CREATE_FREEZER_LOG_ATTEMPT = 'CREATE_FREEZER_LOG_ATTEMPT';
export const CREATE_FREEZER_LOG_SUCCESS = 'CREATE_FREEZER_LOG_SUCCESS';
export const CREATE_FREEZER_LOG_FAIL = 'CREATE_FREEZER_LOG_FAIL';

export const DELETE_FREEZER_LOG_ATTEMPT = 'DELETE_FREEZER_LOG_ATTEMPT';
export const DELETE_FREEZER_LOG_SUCCESS = 'DELETE_FREEZER_LOG_SUCCESS';
export const DELETE_FREEZER_LOG_FAIL = 'DELETE_FREEZER_LOG_FAIL';

export const UPDATE_FREEZER_LOG_ATTEMPT = 'UPDATE_FREEZER_LOG_ATTEMPT';
export const UPDATE_FREEZER_LOG_SUCCESS = 'UPDATE_FREEZER_LOG_SUCCESS';
export const UPDATE_FREEZER_LOG_FAIL = 'UPDATE_FREEZER_LOG_FAIL';
