export const LIST_FOOD_DELIVERY_RECORD_ATTEMPT = 'LIST_FOOD_DELIVERY_RECORD_ATTEMPT';
export const LIST_FOOD_DELIVERY_RECORD_SUCCESS = 'LIST_FOOD_DELIVERY_RECORD_SUCCESS';
export const LIST_FOOD_DELIVERY_RECORD_FAIL = 'LIST_FOOD_DELIVERY_RECORD_FAIL';

export const CREATE_FOOD_DELIVERY_RECORD_ATTEMPT = 'CREATE_FOOD_DELIVERY_RECORD_ATTEMPT';
export const CREATE_FOOD_DELIVERY_RECORD_SUCCESS = 'CREATE_FOOD_DELIVERY_RECORD_SUCCESS';
export const CREATE_FOOD_DELIVERY_RECORD_FAIL = 'CREATE_FOOD_DELIVERY_RECORD_FAIL';

export const DELETE_FOOD_DELIVERY_RECORD_ATTEMPT = 'DELETE_FOOD_DELIVERY_RECORD_ATTEMPT';
export const DELETE_FOOD_DELIVERY_RECORD_SUCCESS = 'DELETE_FOOD_DELIVERY_RECORD_SUCCESS';
export const DELETE_FOOD_DELIVERY_RECORD_FAIL = 'DELETE_FOOD_DELIVERY_RECORD_FAIL';

export const UPDATE_FOOD_DELIVERY_RECORD_ATTEMPT = 'UPDATE_FOOD_DELIVERY_RECORD_ATTEMPT';
export const UPDATE_FOOD_DELIVERY_RECORD_SUCCESS = 'UPDATE_FOOD_DELIVERY_RECORD_SUCCESS';
export const UPDATE_FOOD_DELIVERY_RECORD_FAIL = 'UPDATE_FOOD_DELIVERY_RECORD_FAIL';
