/*
* Record Actions
*/
export const RECORD_CREATE_ATTEMPT = 'RECORD_CREATE_ATTEMPT';
export const RECORD_CREATE_SUCCESS = 'RECORD_CREATE_SUCCESS';
export const RECORD_CREATE_FAIL = 'RECORD_CREATE_FAIL';

export const RECORD_SET_VALUE = 'RECORD_SET_VALUE';
export const RECORD_RESET = 'RECORD_RESET';

export const LIST_FOOD_DELIVERY_RECORD_ATTEMPT = 'LIST_FOOD_DELIVERY_RECORD_ATTEMPT';
export const LIST_FOOD_DELIVERY_RECORD_SUCCESS = 'LIST_FOOD_DELIVERY_RECORD_SUCCESS';
export const LIST_FOOD_DELIVERY_RECORD_FAIL = 'LIST_FOOD_DELIVERY_RECORD_FAIL';

export const DELETE_FOOD_DELIVERY_RECORD_ATTEMPT = 'DELETE_FOOD_DELIVERY_RECORD_ATTEMPT';
export const DELETE_FOOD_DELIVERY_RECORD_SUCCESS = 'DELETE_FOOD_DELIVERY_RECORD_SUCCESS';
export const DELETE_FOOD_DELIVERY_RECORD_FAIL = 'DELETE_FOOD_DELIVERY_RECORD_FAIL';

export const UPDATE_FOOD_DELIVERY_RECORD_ATTEMPT = 'UPDATE_FOOD_DELIVERY_RECORD_ATTEMPT';
export const UPDATE_FOOD_DELIVERY_RECORD_SUCCESS = 'UPDATE_FOOD_DELIVERY_RECORD_SUCCESS';
export const UPDATE_FOOD_DELIVERY_RECORD_FAIL = 'UPDATE_FOOD_DELIVERY_RECORD_FAIL';
