/*
* Record Actions
*/
export const RECORD_CREATE_ATTEMPT = 'RECORD_CREATE_ATTEMPT';
export const RECORD_CREATE_SUCCESS = 'RECORD_CREATE_SUCCESS';
export const RECORD_CREATE_FAIL = 'RECORD_CREATE_FAIL';
export const RECORD_CREATE_SET_VALUE = 'RECORD_CREATE_SET_VALUE';
export const RECORD_CREATE_RESET = 'RECORD_CREATE_RESET';

export const RECORD_LIST_SET_TYPE = 'RECORD_LIST_SET_TYPE';
export const RECORD_LIST_ATTEMPT = 'RECORD_LIST_ATTEMPT';
export const RECORD_LIST_SUCCESS = 'RECORD_LIST_SUCCESS';
export const RECORD_LIST_FAIL = 'RECORD_LIST_FAIL';

export const RECORD_DELETE_ATTEMPT = 'RECORD_DELETE_ATTEMPT';
export const RECORD_DELETE_SUCCESS = 'RECORD_DELETE_SUCCESS';
export const RECORD_DELETE_FAIL = 'RECORD_DELETE_FAIL';
