export const LIST_FREEZER_ITEM_ATTEMPT = 'LIST_FREEZER_ITEM_ATTEMPT';
export const LIST_FREEZER_ITEM_SUCCESS = 'LIST_FREEZER_ITEM_SUCCESS';
export const LIST_FREEZER_ITEM_FAIL = 'LIST_FREEZER_ITEM_FAIL';

export const CREATE_FREEZER_ITEM_ATTEMPT = 'CREATE_FREEZER_ITEM_ATTEMPT';
export const CREATE_FREEZER_ITEM_SUCCESS = 'CREATE_FREEZER_ITEM_SUCCESS';
export const CREATE_FREEZER_ITEM_FAIL = 'CREATE_FREEZER_ITEM_FAIL';

export const DELETE_FREEZER_ITEM_ATTEMPT = 'DELETE_FREEZER_ITEM_ATTEMPT';
export const DELETE_FREEZER_ITEM_SUCCESS = 'DELETE_FREEZER_ITEM_SUCCESS';
export const DELETE_FREEZER_ITEM_FAIL = 'DELETE_FREEZER_ITEM_FAIL';

export const UPDATE_FREEZER_ITEM_ATTEMPT = 'UPDATE_FREEZER_ITEM_ATTEMPT';
export const UPDATE_FREEZER_ITEM_SUCCESS = 'UPDATE_FREEZER_ITEM_SUCCESS';
export const UPDATE_FREEZER_ITEM_FAIL = 'UPDATE_FREEZER_ITEM_FAIL';
